<a href="https://colab.research.google.com/github/jithesh9539/Yelp_Clustering/blob/main/Yelp_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from pprint import pprint # pretty print sometimes helps printing the data more distinguished
import time # to measure execution time
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# For reading and writing datasets
import csv
import json

# For clustering
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

# For plotting
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
data=pd.read_json('yelp_academic_dataset_business.json',lines=True)

In [9]:
data.head()

              business_id  ...                                              hours
0  6iYb2HFDywm3zjuRg0shjw  ...  {'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...
1  tCbdrRPZA0oiIYSmHG3J0w  ...  {'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...
2  bvN78flM8NLprQ1a1y5dRg  ...  {'Thursday': '11:0-18:0', 'Friday': '11:0-18:0...
3  oaepsyvc0J17qwi8cfrOWg  ...                                               None
4  PE9uqAjdw0E4-8mjGl3wVA  ...  {'Monday': '16:0-19:0', 'Tuesday': '16:0-19:0'...

[5 rows x 14 columns]